name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Python deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create backend .env from secrets
        run: |
          cat > backend/.env <<'EOF'
          STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REDIRECT_URI=${{ secrets.STRAVA_REDIRECT_URI }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOF

      - name: Create frontend .env
        run: |
          echo "VITE_API_URL=http://localhost:8000" > frontend/.env

      - name: Backend checks (placeholder)
        run: |
          source venv/bin/activate
          python - <<'PY'
          import os
          required = ["STRAVA_CLIENT_ID","STRAVA_CLIENT_SECRET","SECRET_KEY"]
          missing = [k for k in required if not os.getenv(k)]
          assert not missing, f"Missing envs: {missing}"
          print("Backend env looks OK")
          PY

      - name: Frontend build
        working-directory: frontend
        run: |
          npm ci
          npm run build
