name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Python deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Create backend/.env from GitHub Secrets
        run: |
          mkdir -p backend
          cat > backend/.env <<EOF
          # ==== backend env ====
          STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REDIRECT_URI=${{ secrets.STRAVA_REDIRECT_URI }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          TOKENS_KEY=${{ secrets.TOKENS_KEY }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          EOF

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Frontend deps
        working-directory: frontend
        run: npm ci

      - name: Create frontend/.env from GitHub Secrets
        working-directory: frontend
        run: |
          cat > .env <<EOF
          # ==== frontend env ====
          VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
          EOF

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Upload frontend artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
